import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true

[font]
size = 13
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular"}

[window]
dimensions = {columns = 160, lines = 55}
